[package]
name = "jamscan"
version = "0.0.0"
edition = "2024"
default-run = "jamscan"

[dependencies]
anyhow = "1.0.98"
async-graphql = "7.0.17"
clap = { version = "4.5.37", features = ["derive", "env"] }
dotenv = "0.15.0"
hex = "0.4.3"
redis = "0.32.2"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10"
sqlx = { version = "0.8.5", features = ["runtime-tokio-rustls", "postgres"] }
tokio = "1.44.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

# spacejam dependencies
jamcodec = { git = "https://github.com/spacejamapp/spacejam", branch = "jadex" }
runtime = { git = "https://github.com/spacejamapp/spacejam", package = "spacejam-runtime", branch = "jadex" }
score = { git = "https://github.com/spacejamapp/spacejam", package = "spacejam-core", branch = "jadex" }
spacejam-crypto = { git = "https://github.com/spacejamapp/spacejam", branch = "jadex" }
spacejson = { git = "https://github.com/spacejamapp/spacejam", branch = "jadex" }
jadex = { git = "https://github.com/spacejamapp/spacejam", branch = "jadex" }

# need to fix the auth in github actions if using ssh
# jamcodec = { git = "ssh://git@github.com/spacejamapp/spacejam", branch = "jadex" }
# runtime = { git = "ssh://git@github.com/spacejamapp/spacejam", package = "spacejam-runtime", branch = "jadex" }
# score = { git = "ssh://git@github.com/spacejamapp/spacejam", package = "spacejam-core", branch = "jadex" }
# spacejam-crypto = { git = "ssh://git@github.com/spacejamapp/spacejam", branch = "jadex" }
# spacejson = { git = "ssh://git@github.com/spacejamapp/spacejam", branch = "jadex" }
# jadex = { git = "ssh://git@github.com/spacejamapp/spacejam", branch = "jadex" }
