services:
  postgres:
    image: postgres
    network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jamscan
      POSTGRES_PORT: 5555
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    network_mode: host
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  jamscan:
    image: clearloop/jsvc:latest
    network_mode: host
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./node/light:/data
      - ./data:/shared
    environment:
      DATABASE_URL: postgres://postgres:postgres@localhost:5555/jamscan
      DATA_PATH: /data
      REDIS_URL: redis://localhost:6379
      GRAPHQL_PORT: 3000
      CHAIN: /shared/spec.json
      PRUNE: "true"
      LIGHT: "true"
      BOOTNODE: "eecgwpgwq3noky4ijm4jmvjtmuzv44qvigciusxakq5epnrfj2utb@127.0.0.1:40000"
      RUST_LOG: jamscan=debug,network=debug,spacejam=debug,runtime=debug

  polkajam-0:
    image: clearloop/polkajam:0.1.23
    network_mode: host
    command: -c dev --chain /shared/spec.json run -d /data --dev-validator 0 --port 40000 --rpc-port 19800 --pvm-backend=interpreter
    volumes:
      - ./data:/shared
      - ./node/0:/data
    environment:
      - RUST_LOG=jam_node=trace

  polkajam-1:
    image: clearloop/polkajam:0.1.23
    depends_on:
      - polkajam-0
    network_mode: host
    command: -c dev --chain /shared/spec.json run -d /data --dev-validator 1 --port 40001 --rpc-port 19801 --pvm-backend=interpreter
    volumes:
      - ./data:/shared
      - ./node/1:/data
    environment:
      - RUST_LOG=jam_node=trace

  polkajam-2:
    image: clearloop/polkajam:0.1.23
    depends_on:
      - polkajam-0
    network_mode: host
    command: -c dev --chain /shared/spec.json run -d /data --dev-validator 2 --port 40002 --rpc-port 19802 --pvm-backend=interpreter
    volumes:
      - ./data:/shared
      - ./node/2:/data
    environment:
      - RUST_LOG=jam_node=trace

  polkajam-3:
    image: clearloop/polkajam:0.1.23
    depends_on:
      - polkajam-0
    network_mode: host
    command: -c dev --chain /shared/spec.json run -d /data --dev-validator 3 --port 40003 --rpc-port 19803 --pvm-backend=interpreter
    volumes:
      - ./data:/shared
      - ./node/3:/data
    environment:
      - RUST_LOG=jam_node=trace

  polkajam-4:
    image: clearloop/polkajam:0.1.23
    depends_on:
      - polkajam-0
    network_mode: host
    command: -c dev --chain /shared/spec.json run -d /data --dev-validator 4 --port 40004 --rpc-port 19804 --pvm-backend=interpreter
    volumes:
      - ./data:/shared
      - ./node/4:/data
    environment:
      - RUST_LOG=jam_node=trace

  spacejam:
    image: clearloop/spacejam:0.0.1
    depends_on:
      - polkajam-0
    network_mode: host
    command: run -d /data --chain /shared/spec.json --validator 5 --address 127.0.0.1:40005
    volumes:
      - ./data:/shared
      - ./node/5:/data
    environment:
      - RUST_LOG=spacejam=debug,runtime=debug,network=debug

volumes:
  postgres_data:
  migrations:
  data:
  node:
